branches:
  only:
    - master
    - /^(fix|feature|dev)\//
language: node_js
node_js:
  - "node"
sudo: false
install:
  - npm install
  - npm install -g codecov
script:
  - npm run coverage
after_success:
  - codecov
